In [1]:
import pandas as pd
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
import random
import datetime as dt
import statsmodels.api as sm

df_f = pd.read_csv(r'C:\Users\Joyce Huang\Downloads\Innovation challenge\final-financial.csv')
df_s = pd.read_csv(r'C:\Users\Joyce Huang\Downloads\Innovation challenge\soybean-oil-price.csv')
df_n = pd.read_csv(r'C:\Users\Joyce Huang\Downloads\Innovation challenge\news.csv')
df_s = df_s.dropna()
print(type(df_f['Date'][1]))
df_f['Date'] = pd.to_datetime(df_f['Date'])
df_s['Date'] = pd.to_datetime(df_s['Date'])
df_n['Date'] = pd.to_datetime(df_n['publish_time'])
print(type(df_f['Date'][1]))
print(type(df_s['Date'][1]))
print(type(df_n['Date'][1]))
df_s = df_s.sort_values(by=['Date'], ascending=True).reset_index()
display(df_f)
display(df_s)
display(df_n)

<class 'str'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

          Date     sp500      nadq  crude_oil  dow_jones       usd
0   2021-01-01       NaN       NaN        NaN        NaN       NaN
1   2021-01-04 -1.996479 -1.903586  -2.500008  -2.373722 -1.273207
2   2021-01-05 -1.905114 -1.766484  -2.218646  -2.269819 -1.142662
3   2021-01-06 -1.830935 -1.855416  -2.133385  -1.998582 -1.187322
4   2021-01-07 -1.636946 -1.483746  -2.109025  -1.867405 -0.937163
..         ...       ...       ...        ...        ...       ...
256 2021-12-27  1.804995  1.706067   0.904345   1.392172  2.547886
257 2021-12-28  1.788124  1.604199   0.954284   1.451544  2.359251
258 2021-12-29  1.811514  1.586565   1.024928   1.507562  2.346759
259 2021-12-30  1.761562  1.558509   1.077303   1.451461  2.173116
260 2021-12-31  1.717815  1.448621   0.860496   1.414427  2.134390

[261 rows x 6 columns]

     index       Date  Price   Open   High    Low     Vol Change %
0      260 2021-01-04  42.93  43.63  44.36  42.50   0.95K    1.15%
1      259 2021-01-05  44.36  43.30  44.64  43.10   0.55K    3.33%
2      258 2021-01-06  44.39  44.87  45.27  44.38   0.52K    0.07%
3      257 2021-01-07  44.35  44.50  44.55  43.65   0.35K   -0.09%
4      256 2021-01-08  43.76  44.60  44.67  43.89   0.21K   -1.33%
..     ...        ...    ...    ...    ...    ...     ...      ...
244      4 2021-12-27  56.72  56.00  57.43  55.64  22.90K    2.22%
245      3 2021-12-28  56.55  56.70  57.69  56.17  17.23K   -0.30%
246      2 2021-12-29  56.70  56.54  57.30  56.18  13.82K    0.27%
247      1 2021-12-30  55.85  56.71  56.95  55.35   6.08K   -1.50%
248      0 2021-12-31  56.30  55.82  56.63  55.71   1.07K    0.81%

[249 rows x 8 columns]

,Unnamed: 0,news_title,news_content,publish_time,polarity,subjectivity,year,Date
0,8,Japan: Utilization of Food-Grade Soybeans in J...,â€¦ in Japan This report provides an overview of...,"March 26, 2021",0.107143,0.264286,2021,2021-03-26
1,15,India: India Clarifies and Extends its Import ...,â€¦ India: India Clarifies and Extends its Impor...,"September 20, 2021",0.000000,0.000000,2021,2021-09-20
2,16,China: China Notified Draft National Standard ...,â€¦ Draft National Standard for Soybeans The dra...,"March 24, 2021",0.000000,0.000000,2021,2021-03-24
3,22,India: India Officially Permits Limited Soybea...,â€¦ India: India Officially Permits Limited Soyb...,"August 30, 2021",-0.071429,0.142857,2021,2021-08-30
4,23,India: India - A Thumbs Up for Soybean Meal Im...,â€¦ India: India - A Thumbs Up for Soybean Meal ...,"August 13, 2021",0.000000,1.000000,2021,2021-08-13
5,29,China: GE Corn and Soybean Registration Standa...,â€¦ China: GE Corn and Soybean Registration Stan...,"December 9, 2021",0.000000,0.750000,2021,2021-12-09
6,30,Mexico: Mexico Announces Temporary Tariff Rate...,â€¦ Mexico published a tariff rate quota (TRQ) a...,"October 19, 2021",0.000000,0.000000,2021,2021-10-19
7,32,China: China Notified Draft National Food Safe...,â€¦ Food Safety Standard for Soybeans The draft ...,"March 5, 2021",0.000000,0.000000,2021,2021-03-05
8,35,India: Indian Government Imposes Stock Limits ...,â€¦ India: Indian Government Imposes Stock Limit...,"December 31, 2021",0.000000,0.100000,2021,2021-12-31
9,36,India: India Approves Additional Ports for Bul...,â€¦ India: India Approves Additional Ports for B...,"September 20, 2021",0.200000,0.400000,2021,2021-09-20
10,39,Costa Rica: Hurricane Ida Disruption to Corn a...,â€¦ Costa Rica: Hurricane Ida Disruption to Corn...,"November 8, 2021",0.200000,0.810000,2021,2021-11-08
11,40,2021 U.S. Soybean Outlook Remains Strong After...,â€¦ 2021 U.S. Soybean Outlook Remains Strong Aft...,"June 29, 2021",0.273333,0.526667,2021,2021-06-29
12,50,Brazil: Oilseeds and Products Update,â€¦ and Products Update Post lowered its 2021/22...,"January 18, 2022",0.433333,0.733333,2022,2022-01-18
13,51,Brazil: Oilseeds and Products Update,â€¦ Products Update Post maintains its 2020/21 f...,"January 6, 2021",0.000000,0.400000,2021,2021-01-06
14,54,China: Oilseeds and Products Update,â€¦ China: Oilseeds and Products Update Soybean ...,"September 7, 2021",-0.119048,0.154762,2021,2021-09-07
15,58,China: Oilseeds and Products Update,â€¦ China: Oilseeds and Products Update Chinaâ€™s ...,"November 4, 2021",0.030000,0.470000,2021,2021-11-04
16,59,Vietnam: Oilseeds and Products Annual,â€¦ Vietnam: Oilseeds and Products Annual Soybea...,"April 16, 2021",0.000000,0.100000,2021,2021-04-16
17,63,Paraguay: Oilseeds and Products Annual,â€¦ Paraguay: Oilseeds and Products Annual 2021/...,"April 13, 2021",0.150000,0.650000,2021,2021-04-13
18,64,Indonesia: Oilseeds and Products Update,â€¦ Indonesia: Oilseeds and Products Update To s...,"February 4, 2021",0.000000,0.000000,2021,2021-02-04
19,70,Egypt: Oilseeds and Products Annual,â€¦ year 2019/20 was another record year for U.S...,"April 6, 2021",0.400000,0.900000,2021,2021-04-06
20,73,Brazil: Oilseeds and Products Update,"â€¦ Oilseeds and Products Update For 2021/22, Po...","July 2, 2021",0.200000,0.200000,2021,2021-07-02
21,74,Vietnam: Oilseeds and Products Update,â€¦ regulations and restrictions. Post revises i...,"October 5, 2021",0.005000,0.405000,2021,2021-10-05
22,75,South Korea: Oilseeds and Products Annual,â€¦ South Korea: Oilseeds and Products Annual MY...,"March 5, 2021",-0.086667,0.360000,2021,2021-03-05
23,80,Brazil: Oilseeds and Products Update,â€¦ and Products Update Post lowered its 2021/22...,"February 14, 2022",0.216667,0.616667,2022,2022-02-14
24,90,Japan: Oilseeds and Products Annual,"â€¦ Japan increased rapeseed imports and crush, ...","April 2, 2021",0.000000,0.100000,2021,2021-04-02
25,91,Japan: Oilseeds and Products Annual,"â€¦ Japan increased rapeseed imports and crush, ...","April 2, 2021",0.000000,0.100000,2021,2021-04-02
26,104,Pakistan: Oilseeds and Products Annual,â€¦ developed the infrastructure to shift away f...,"April 5, 2021",0.250000,0.600000,2021,2021-04-05
27,110,China: Oilseeds and Products Update,â€¦ China: Oilseeds and Products Update FAS Chin...,"July 1, 2021",0.088889,0.544444,2021,2021-07-01

In [2]:
merge = pd.merge(df_f, df_s, on ='Date', how ="outer")
merge = merge.drop('index',axis=1)
merge = pd.merge(merge, df_n, on ='Date', how ="outer")
merge = merge.drop(['Unnamed: 0','news_content','publish_time','year','Open','news_title'],axis=1)
merge = merge.sort_values(by=['Date'], ascending=True)
merge = merge[merge['Date'].dt.strftime('%Y')=='2021']

merge['Vol'] = merge['Vol'].str.replace('K', '')
merge['change'] = merge['Change %'].str.replace('%', '')
merge = merge.drop('Change %',axis=1)
display(merge)

e = ['Date','polarity','subjectivity']
df2 = merge[e]

,Date,sp500,nadq,crude_oil,dow_jones,usd,Price,High,Low,Vol,polarity,subjectivity,change
0,2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-04,-1.996479,-1.903586,-2.500008,-2.373722,-1.273207,42.93,44.36,42.50,0.95,NaN,NaN,1.15
2,2021-01-05,-1.905114,-1.766484,-2.218646,-2.269819,-1.142662,44.36,44.64,43.10,0.55,NaN,NaN,3.33
3,2021-01-06,-1.830935,-1.855416,-2.133385,-1.998582,-1.187322,44.39,45.27,44.38,0.52,0.0,0.4,0.07
4,2021-01-07,-1.636946,-1.483746,-2.109025,-1.867405,-0.937163,44.35,44.55,43.65,0.35,NaN,NaN,-0.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,2021-12-27,1.804995,1.706067,0.904345,1.392172,2.547886,56.72,57.43,55.64,22.90,NaN,NaN,2.22
260,2021-12-28,1.788124,1.604199,0.954284,1.451544,2.359251,56.55,57.69,56.17,17.23,NaN,NaN,-0.30
261,2021-12-29,1.811514,1.586565,1.024928,1.507562,2.346759,56.70,57.30,56.18,13.82,NaN,NaN,0.27
262,2021-12-30,1.761562,1.558509,1.077303,1.451461,2.173116,55.85,56.95,55.35,6.08,NaN,NaN,-1.50
263,2021-12-31,1.717815,1.448621,0.860496,1.414427,2.134390,56.30,56.63,55.71,1.07,0.0,0.1,0.81

In [3]:
df = merge[['sp500','nadq','crude_oil','dow_jones','usd','Price','High','Low','Vol','change']]
from sklearn.impute import KNNImputer
import pandas as pd

imputer = KNNImputer()
imputed_data = imputer.fit_transform(df)
df_temp = pd.DataFrame(imputed_data)
df_temp.columns = df.columns
df['sp500'] = df_temp['sp500']
df['nadq'] = df_temp['nadq']
df['crude_oil'] = df_temp['crude_oil']
df['dow_jones'] = df_temp['dow_jones']
df['Price'] = df_temp['Price']
df['High'] = df_temp['High']
df['Low'] = df_temp['Low']
df['Vol'] = df_temp['Vol']
df['change'] = df_temp['change']
df['usd'] = df_temp['usd']
display(df)

<ipython-input-3-8158565f916f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sp500'] = df_temp['sp500']
<ipython-input-3-8158565f916f>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['nadq'] = df_temp['nadq']
<ipython-input-3-8158565f916f>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crude_oil'] = df_temp['crude_oil']
<ipython-input-3-8158565f916f>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['dow_jones'] = df_temp['dow_jones']
<ipython-input-3-8158565f916f>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price'] = df_temp['Price']
<ipython-input-3-8158565f916f>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['High'] = df_temp['High']
<ipython-input-3-8158565f916f>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Low'] = df_temp['Low']
<ipython-input-3-8158565f916f>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Vol'] = df_temp['Vol']
<ipython-input-3-8158565f916f>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['change'] = df_temp['change']
<ipython-input-3-8158565f916f>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['usd'] = df_temp['usd']

,sp500,nadq,crude_oil,dow_jones,usd,Price,High,Low,Vol,change
0,-0.004764,-0.004969,0.000043,-0.006449,-0.004594,58.084422,59.018645,57.286972,27.470916,0.120757
1,-1.996479,-1.903586,-2.500008,-2.373722,-1.273207,42.930000,44.360000,42.500000,0.950000,1.150000
2,-1.905114,-1.766484,-2.218646,-2.269819,-1.142662,44.360000,44.640000,43.100000,0.550000,3.330000
3,-1.830935,-1.855416,-2.133385,-1.998582,-1.187322,44.390000,45.270000,44.380000,0.520000,0.070000
4,-1.636946,-1.483746,-2.109025,-1.867405,-0.937163,44.350000,44.550000,43.650000,0.350000,-0.090000
...,...,...,...,...,...,...,...,...,...,...
259,1.804995,1.706067,0.904345,1.392172,2.547886,56.720000,57.430000,55.640000,22.900000,2.220000
260,1.788124,1.604199,0.954284,1.451544,2.359251,56.550000,57.690000,56.170000,17.230000,-0.300000
261,1.811514,1.586565,1.024928,1.507562,2.346759,56.700000,57.300000,56.180000,13.820000,0.270000
262,1.761562,1.558509,1.077303,1.451461,2.173116,55.850000,56.950000,55.350000,6.080000,-1.500000
263,1.717815,1.448621,0.860496,1.414427,2.134390,56.300000,56.630000,55.710000,1.070000,0.810000

In [ ]:
df = pd.concat([df,df2], axis=1)
df = df[['Date','sp500','nadq','crude_oil','dow_jones','usd','Price','High','Low','Vol','change','polarity','subjectivity']]
df = df.fillna(0)
df

In [5]:
df.to_csv(r'C:\Users\Joyce Huang\Downloads\Innovation challenge\financial-soy-news.csv')

In [18]:
from sklearn.model_selection import train_test_split,cross_validate, GridSearchCV
from sklearn.metrics import roc_curve, auc,recall_score,precision_score,plot_roc_curve,accuracy_score
import xgboost as xgb

X = df.drop(['Date','Price','High','Low','Vol'],axis=1)
Y = df['Price']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

def algorithm_pipeline(X_train, X_test, y_train, y_test, 
                       model, param_grid, cv=5, scoring_fit='neg_mean_squared_error',
                       do_probabilities = False):
    gs = GridSearchCV(
        estimator=model,
        param_grid=param_grid, 
        cv=cv, 
        n_jobs=-1, 
        scoring=scoring_fit,
        verbose=2
    )
    fitted_model = gs.fit(X_train, y_train)
    
    if do_probabilities:
      pred = fitted_model.predict_proba(X_test)
    else:
      pred = fitted_model.predict(X_test)
    
    return fitted_model, pred

model = xgb.XGBRegressor()
param_grid = {
    'learning_rate': (0.05, 0.10, 0.15),
    'n_estimators': [100, 150,200,250,300],
    'max_depth': [15,20,30,40,50]
}

model, pred = algorithm_pipeline(X_train, X_test, y_train, y_test, model, 
                                 param_grid, cv=5)

# Root Mean Squared Error
print(np.sqrt(-model.best_score_))
print(model.best_params_)

Fitting 5 folds for each of 75 candidates, totalling 375 fits
2.43325939947435
{'learning_rate': 0.05, 'max_depth': 15, 'n_estimators': 200}

In [19]:
print(model)

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None,
                                    enable_categorical=False, gamma=None,
                                    gpu_id=None, importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, max_delta_step=None,
                                    max_depth=None, min_child_weight=None,
                                    missing=nan, monotone_constraints=None,
                                    n...one,
                                    num_parallel_tree=None, predictor=None,
                                    random_state=None, reg_alpha=None,
                                    reg_lambda=None, scale_pos_weight=None,
                                    subsample=None, tree_method=None,
                                    validate_parameters=None, verbosity=None),
             n_jobs=-1,
             param_grid={'learning_rate': (0.05, 0.1, 0.15),
                         'max_depth': [15, 20, 30, 40, 50],
                         'n_estimators': [100, 150, 200, 250, 300]},
             scoring='neg_mean_squared_error', verbose=2)

In [20]:
from sklearn.metrics import mean_squared_error

print(pred)
print('Test MSE = {}'.format(round(mean_squared_error(y_test, pred),4)))

[68.37888  66.106415 54.27173  64.51862  56.687763 55.90548  55.30979
 59.302383 54.760956 50.068638 68.53138  43.4892   58.310802 54.640575
 57.187733 63.707413 65.48362  59.01573  65.45091  66.29783  55.175358
 54.787346 54.087124 59.39748  54.732502 67.31618  59.010235 58.4393
 63.915985 58.512264 60.998592 47.070908 66.23711  60.88499  60.444298
 57.91756  44.387863 58.496258 61.289692 67.80222  64.29048  61.44599
 51.737053 58.062405 65.309265 54.123207 47.81567  59.74392  64.562195
 43.521862 61.867085 59.944946 61.524403]
Test MSE = 5.0121